### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '.snakemake'

### ISSUE THREAD

**Issue by spencel** [nextstrain/ncov#1041]
**Current Behavior**
The following command doesn't work:
```
nextstrain build . --configfile ncov-tutorial/example-data.yaml
```
**Expected behavior**
I just wanted to start the tutorial.

**How to reproduce**
```
~/ncov$ nextstrain build . --configfile ncov-tutorial/example-data.yaml
Traceback (most recent call last):
  File "/usr/local/bin/snakemake", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/snakemake/__init__.py", line 2013, in main
    success = snakemake(
  File "/usr/local/lib/python3.10/site-packages/snakemake/__init__.py", line 423, in snakemake
    logger.setup_logfile()
  File "/usr/local/lib/python3.10/site-packages/snakemake/logging.py", line 135, in setup_logfile
    os.makedirs(os.path.join(".snakemake", "log"), exist_ok=True)
  File "/usr/local/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '.snakemake'
```

**Possible solution**
I'm not sure. This system is quite abstracted.

**Your environment: if running Nextstrain locally**
 - Operating system:
-- Distributor ID:	Ubuntu
-- Description:	Ubuntu 22.04.1 LTS
-- Release:	22.04
-- Codename:	jammy
 - Browser:
 - Version (e.g. `auspice 2.7.0`):

**Comment by spencel** [comment]
Wait, maybe I skipped a step: https://docs.nextstrain.org/en/latest/install.html

**Comment by spencel** [comment]
It worked! I thought I just had another broken Ubuntu installation.

**Comment by tsibley** [comment]
Glad you were able to resolve this!
