### ISSUE TITLE
Failed in jobid 17 due to an eeror of clade

### ISSUE THREAD

**Issue by ElwynWang** [nextstrain/ncov#167]
Hi,

When I run this project, I suffered an error as follows. I will appreciate if anyone could help me to solve this issue or give some suggestions.

Validating schema of 'results/aa_muts.json'...
Traceback (most recent call last):
  File "/home/anaconda3/envs/nextstrain/bin/augur", line 8, in <module>
    sys.exit(main())
  File "/home/anaconda3/envs/nextstrain/lib/python3.6/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/home/anaconda3/envs/nextstrain/lib/python3.6/site-packages/augur/__init__.py", line 74, in run
    return args.__command__.run(args)
  File "/home/anaconda3/envs/nextstrain/lib/python3.6/site-packages/augur/clades.py", line 211, in run
    clade_membership = assign_clades(clade_designations, all_muts, tree, ref)
  File "/home/anaconda3/envs/nextstrain/lib/python3.6/site-packages/augur/clades.py", line 147, in assign_clades
    if is_node_in_clade(clade_alleles, node, ref):
  File "/home/anaconda3/envs/nextstrain/lib/python3.6/site-packages/augur/clades.py", line 73, in is_node_in_clade
    state = ref[gene][pos]
TypeError: list indices must be integers or slices, not float
[Sat Mar 14 11:26:48 2020]
Error in rule clades:
    jobid: 17
    output: results/clades.json
    shell:
      
        augur clades --tree results/tree.nwk             --mutations results/nt_muts.json results/aa_muts.json             --clades config/clades.tsv             --output-node-data results/clades.json
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by emmahodcroft** [comment]
Hi @ElwynWang. I pushed an update a little while ago which should fix this. The `clades` file had a line which was separated by spaces instead of tabs. This should be fixed now. Try pulling and re-running?

**Comment by emmahodcroft** [comment]
@ElwynWang your issue should be fixed, but re-open if you need.
