### ISSUE TITLE
ERROR: reference sequence not found. looking for config/reference.gb

### ISSUE THREAD

**Issue by lpipes** [nextstrain/ncov#432]
Hello, where can I download the "reference.gb" file? I am trying to use the assign_clades.py script.

python assign_clades.py --sequences seq.fasta
ERROR: reference sequence not found. looking for config/reference.gb
Traceback (most recent call last):
  File "assign_clades.py", line 33, in <module>
    ref = SeqIO.read(refname, 'genbank')
  File "/home/lenore/bin/anaconda2/lib/python3.8/site-packages/Bio/SeqIO/__init__.py", line 744, in read
    first = next(iterator)
  File "/home/lenore/bin/anaconda2/lib/python3.8/site-packages/Bio/GenBank/Scanner.py", line 514, in parse_records
    with as_handle(handle, "rU") as handle:
  File "/home/lenore/bin/anaconda2/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/lenore/bin/anaconda2/lib/python3.8/site-packages/Bio/File.py", line 120, in as_handle
    with open(handleish, mode, **kwargs) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'config/reference.gb'`

**Comment by rneher** [comment]
Hi @lpipes 

from where are you calling this script? you need to call it from the top-level of the ncov repository such that the folder `config` exists.

**Comment by lpipes** [comment]
oh ok I was just calling the script directly

**Comment by rneher** [comment]
this should work
`cd ncov`
`python assign_clades.py --sequences example_data/sequences.fasta --output tmp.tsv`

**Comment by rneher** [comment]
closing this, assuming it worked. please reopen if the issue persists.
