### ISSUE TITLE
scipy error in priorities.py on the latest GISAID dump

### ISSUE THREAD

**Issue by asl** [nextstrain/ncov#512]
**Current Behavior**
Running ncov on the latest GISAID dump always results in:
```
Done reading the alignments.
Traceback (most recent call last):
  File "scripts/priorities.py", line 163, in <module>
    d = np.array(calculate_distance_matrix(context_seqs_dict['snps'], focal_seqs_dict['snps'], consensus = context_seqs_dict['consensus']))
  File "scripts/priorities.py", line 115, in calculate_distance_matrix
    d = d + (1*(sparse_matrix_A==103) * (sparse_matrix_B.transpose()==103))
  File "/home/akorobeynikov/miniconda3/envs/nextstrain/lib/python3.6/site-packages/scipy/sparse/base.py", line 480, in __mul__
    return self._mul_sparse_matrix(other)
  File "/home/akorobeynikov/miniconda3/envs/nextstrain/lib/python3.6/site-packages/scipy/sparse/compressed.py", line 509, in _mul_sparse_matrix
    np.asarray(other.indices, dtype=idx_dtype))
RuntimeError: nnz of the result is too large
```

**How to reproduce**
Steps to reproduce the current behavior:
1. Dowload the latest data from GISAID
2. Preprocess it via `normalize_gisaid_fasta.sh`
3. Use the following set of builds:
```

builds:
  europe_russia_saint-petersburg:
    subsampling_scheme: division
    region: Europe
    country: Russia
    division: Saint-Petersburg

  europe_russia:
    subsampling_scheme: country
    region: Europe
    country: Russia

  europe:
    subsampling_scheme: region                                                                                                                                                        region: Europe

  global:
    subsampling_scheme: region_global
    region: global
```

**Comment by emmahodcroft** [comment]
Hi @asl, thanks for posting this. We ran into this error ourselves last night, but we weren't able to determine if this is a size issue (the comparisons have just gotten too large) or if some particular sequence is throwing this off. We found changing our subsampling criteria solved the problem - but it's unclear which of the reasons above it might have been (or something else entirely).

Has the size of the run you're trying to do changed at all? (Is it larger this time than it was the last time you've run it?) Or would it be the same size (number of sequences) but just new ones? Perhaps this can help us get to the bottom of what's happening here.

**Comment by emmahodcroft** [comment]
Tagging @rneher so he can follow too.

**Comment by asl** [comment]
Size is likely the culprit, however I have not looked inside yet. Will you please share your changes of subsampling criteria so I can compare the SNP distance matrices?

**Comment by emmahodcroft** [comment]
Originally the build would have had over 17,000 sequences 😬 
We added some subsampling now it's 5,700 or so. 
Unfortunately not sure at what threshold it broke while slowly climbing up to the 17,000

**Comment by trvrb** [comment]
I believe this issue has been resolved in the latest `ncov` workflow, but please @asl re-open if it's still a problem.

**Comment by michalkowalski94** [comment]
Hi there, latest pull
Same issue

**Comment by ericenns** [comment]
I am also getting the same issue. Latest branch of master and latest pull of data from Gisaid.

**Comment by asl** [comment]
Yes, same issue. Unfortunately I cannot reopen the issue. Tagging @trvrb @emmahodcroft

**Comment by ericenns** [comment]
I changed workflow/env/nextstrain.yml to the following:

```
name: nextstrain                                                                                                                                                                                                                                                                                                             channels:                                                                                                                                                                                                                                                                                                                    - bioconda                                                                                                                                                                                                                                                                                                                   - defaults                                                                                                                                                                                                                                                                                                                   dependencies:                                                                                                                                                                                                                                                                                                                - cvxopt                                                                                                                                                                                                                                                                                                                     - datrie                                                                                                                                                                                                                                                                                                                     - fasttree                                                                                                                                                                                                                                                                                                                   - iqtree                                                                                                                                                                                                                                                                                                                     - mafft=7.471                                                                                                                                                                                                                                                                                                                - pandas                                                                                                                                                                                                                                                                                                                     - psutil                                                                                                                                                                                                                                                                                                                     - python=3.7*                                                                                                                                                                                                                                                                                                                - scipy=1.6.0                                                                                                                                                                                                                                                                                                                - nodejs=10                                                                                                                                                                                                                                                                                                                  - raxml                                                                                                                                                                                                                                                                                                                      - vcftools                                                                                                                                                                                                                                                                                                                   - git                                                                                                                                                                                                                                                                                                                        - pip                                                                                                                                                                                                                                                                                                                        - pip:                                                                                                                                                                                                                                                                                                                         
  - awscli==1.18.45                                                                                                                                                                                                                                                                                                            
  - nextstrain-augur==10.3.0                                                                                                                                                                                                                                                                                                   
  - nextstrain-cli==1.16.5                                                                                                                                                                                                                                                                                                     
   - rethinkdb==2.3.0.post6 
```

Basically updated to python 3.7.* and added in `scipy=1.6.0` and it has not failed yet. Before it would fail the proximity_score job in <3min and the job has been running for ~8min so far. Will report back if it is successful. My idea for bumping scipy version was from this issue https://github.com/scipy/scipy/issues/12495
