### ISSUE TITLE
ncov conda environment failure on creation

### ISSUE THREAD

**Issue by wasade** [nextstrain/ncov#539]
**Current Behavior**
The conda environment configuration for ncov fails to create a working environment. An error indicating that Cython is missing is reported (see end of issue). If Cython is added into the config prior to environment creation, the environment fails due to a Python 3.7 requirement (not shown). 

**Expected behavior**
It should be possible to setup a ncov environment by following the setup documentation.

**How to reproduce**
Steps to reproduce the current behavior:
1. Go to "https://nextstrain.github.io/ncov/setup"
2. Copy and paste the first two code cells into a terminal

**Possible solution**
Following failure, a manual install of the missing pip dependencies seemed to work. It's not obvious why that works when conda didn't.

**Your environment: if running Nextstrain locally**
 - Operating system: Centos 6.6
 - Conda 4.9.2

**Conda error**

```bash
$ curl http://data.nextstrain.org/nextstrain.yml --compressed -o nextstrain.yml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   300  100   300    0     0   2930      0 --:--:-- --:--:-- --:--:--  6976
$ md5sum nextstrain.yml
0b615193021c854cae13c910b5d4417c  nextstrain.yml
$ conda env create -f nextstrain.yml

Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: \ Ran pip subprocess with arguments:
['/home/mcdonadt/miniconda3/envs/nextstrain/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/mcdonadt/condaenv.jju_bmce.requirements.txt']
Pip subprocess output:
Downloading/unpacking awscli (from -r /home/mcdonadt/condaenv.jju_bmce.requirements.txt (line 1))
  Running setup.py egg_info for package awscli
    /tmp/pip_build_dtmcdonald/awscli/setup.py:11: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.

Downloading/unpacking nextstrain-augur (from -r /home/mcdonadt/condaenv.jju_bmce.requirements.txt (line 2))
  Running setup.py egg_info for package nextstrain-augur
    /tmp/pip_build_dtmcdonald/nextstrain-augur/setup.py:11: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
      This may be due to an out of date pip.
Downloading/unpacking nextstrain-cli (from -r /home/mcdonadt/condaenv.jju_bmce.requirements.txt (line 3))
  Running setup.py egg_info for package nextstrain-cli
    /tmp/pip_build_dtmcdonald/nextstrain-cli/setup.py:11: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.

Downloading/unpacking rethinkdb==2.3.0.post6 (from -r /home/mcdonadt/condaenv.jju_bmce.requirements.txt (line 4))
  Running setup.py egg_info for package rethinkdb
    /tmp/pip_build_dtmcdonald/rethinkdb/setup.py:11: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
      import os, setuptools, sys
Downloading/unpacking snakemake==5.26.1 (from -r /home/mcdonadt/condaenv.jju_bmce.requirements.txt (line 5))
  Running setup.py egg_info for package snakemake
    /tmp/pip_build_dtmcdonald/snakemake/setup.py:11: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
      import versioneer
Downloading/unpacking botocore==1.19.59 (from awscli->-r /home/mcdonadt/condaenv.jju_bmce.requirements.txt (line 1))
  Running setup.py egg_info for package botocore
    /tmp/pip_build_dtmcdonald/botocore/setup.py:11: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.

    warning: no files found matching 'botocore/vendored/requests/cacert.pem'
    no previously-included directories found matching 'docs/build'
Downloading/unpacking docutils<0.16,>=0.10 (from awscli->-r /home/mcdonadt/condaenv.jju_bmce.requirements.txt (line 1))
  Running setup.py egg_info for package docutils
    /tmp/pip_build_dtmcdonald/docutils/setup.py:11: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
      from distutils.command.build import build
    warning: no files found matching 'MANIFEST'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    warning: no previously-included files matching '*~' found under directory '*'
    warning: no previously-included files matching '.DS_Store' found under directory '*'
Downloading/unpacking s3transfer<0.4.0,>=0.3.0 (from awscli->-r /home/mcdonadt/condaenv.jju_bmce.requirements.txt (line 1))
  Running setup.py egg_info for package s3transfer
    /tmp/pip_build_dtmcdonald/s3transfer/setup.py:11: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.

Downloading/unpacking PyYAML<5.4,>=3.10 (from awscli->-r /home/mcdonadt/condaenv.jju_bmce.requirements.txt (line 1))
  Running setup.py egg_info for package PyYAML
    /tmp/pip_build_dtmcdonald/PyYAML/setup.py:11: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
      support, capable extension API, and sensible error messages.  PyYAML
Downloading/unpacking colorama<0.4.4,>=0.2.5 (from awscli->-r /home/mcdonadt/condaenv.jju_bmce.requirements.txt (line 1))
  Downloading colorama-0.4.3.tar.gz
  Running setup.py egg_info for package colorama
    /tmp/pip_build_dtmcdonald/colorama/setup.py:11: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
      from distutils.core import setup
Downloading/unpacking rsa<=4.5.0,>=3.1.2 (from awscli->-r /home/mcdonadt/condaenv.jju_bmce.requirements.txt (line 1))
  Running setup.py egg_info for package rsa
    /tmp/pip_build_dtmcdonald/rsa/setup.py:11: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
      #  Unless required by applicable law or agreed to in writing, software
Downloading/unpacking bcbio-gff==0.6.*,>=0.6.0 (from nextstrain-augur->-r /home/mcdonadt/condaenv.jju_bmce.requirements.txt (line 2))
  Downloading bcbio-gff-0.6.6.tar.gz
  Running setup.py egg_info for package bcbio-gff
    /tmp/pip_build_dtmcdonald/bcbio-gff/setup.py:11: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
      exec(line.strip())
Downloading/unpacking biopython<=1.76,>=1.67 (from nextstrain-augur->-r /home/mcdonadt/condaenv.jju_bmce.requirements.txt (line 2))
  Running setup.py egg_info for package biopython
    /tmp/pip_build_dtmcdonald/biopython/setup.py:11: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
      the PyPI archive with::
    warning: no previously-included files found matching 'Tests/Gck/DGVC_GCK.zip'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.py{}' found anywhere in distribution
    warning: no previously-included files matching '*.py-e' found anywhere in distribution
    warning: no previously-included files found matching 'Bio/Align/substitution_matrices/data/README.txt'
Downloading/unpacking jsonschema==3.*,>=3.0.0 (from nextstrain-augur->-r /home/mcdonadt/condaenv.jju_bmce.requirements.txt (line 2))
  Running setup.py egg_info for package jsonschema
    /tmp/pip_build_dtmcdonald/jsonschema/setup.py:11: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
Downloading/unpacking packaging>=19.2 (from nextstrain-augur->-r /home/mcdonadt/condaenv.jju_bmce.requirements.txt (line 2))
  Running setup.py egg_info for package packaging
    /tmp/pip_build_dtmcdonald/packaging/setup.py:11: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
      # setuptools and distutils with a single setup.py, in this specific instance
    warning: no previously-included files found matching 'noxfile.py'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching 'dev-requirements.txt'
    warning: no previously-included files found matching 'tests/build-hello-world.sh'
    warning: no previously-included files found matching 'tests/hello-world.c'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'tasks'
Downloading/unpacking pandas==1.*,>=1.0.0 from https://files.pythonhosted.org/packages/11/1c/b0bc154996617eae877ff267fcf84e55e6c6808dbade0da206f0419dd483/pandas-1.2.1.tar.gz#sha256=5527c5475d955c0bc9689c56865aaa2a7b13c504d6c44f0aadbf57b565af5ebd (from nextstrain-augur->-r /home/mcdonadt/condaenv.jju_bmce.requirements.txt (line 2))
  Running setup.py egg_info for package pandas
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip_build_dtmcdonald/pandas/setup.py", line 761, in <module>
        setup_package()
      File "/tmp/pip_build_dtmcdonald/pandas/setup.py", line 731, in setup_package
        ext_modules=maybe_cythonize(extensions, compiler_directives=directives),
      File "/tmp/pip_build_dtmcdonald/pandas/setup.py", line 496, in maybe_cythonize
        raise RuntimeError("Cannot cythonize without Cython installed.")
    RuntimeError: Cannot cythonize without Cython installed.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip_build_dtmcdonald/pandas/setup.py", line 761, in <module>

    setup_package()

  File "/tmp/pip_build_dtmcdonald/pandas/setup.py", line 731, in setup_package

    ext_modules=maybe_cythonize(extensions, compiler_directives=directives),

  File "/tmp/pip_build_dtmcdonald/pandas/setup.py", line 496, in maybe_cythonize

    raise RuntimeError("Cannot cythonize without Cython installed.")

RuntimeError: Cannot cythonize without Cython installed.

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_dtmcdonald/pandas
Storing complete log in /tmp/tmpmk6a8jit

Pip subprocess error:

failed

CondaEnvException: Pip failed
```

**Comment by ericenns** [comment]
@wasade try this instead https://github.com/nextstrain/ncov/raw/master/workflow/envs/nextstrain.yaml

It has a different md5sum, I have found that the nextstrain ncov docs and website are lagging behind.

**Comment by huddlej** [comment]
Thank you for sharing this issue, @wasade. There are a couple of issues here related to conda/pip dependencies. In the short term, one solution that might work for you right away is to use the [Nextstrain CLI](https://docs.nextstrain.org/en/latest/tutorials/quickstart.html#install-the-nextstrain-cli). The CLI manages the Nextstrain environment through a Docker image that can be easily updated with the `nextstrain update` command. The CLI also lightly wraps the Snakemake interface, so you can run `nextstrain build --cpus 4 . --profile ./my_profiles/getting_started` instead of `snakemake --cores 4 --profile ./my_profiles/getting_started`.

If you prefer to use a conda environment, here is my best guess for what is happening when you install the Nextstrain environment and some ideas for how we can solve the problem:

1. The conda environment requires Python 3.6
2. pandas only supports Python >=3.7.1, so prebuilt wheels for the latest pandas are not available for Python 3.6
3. The conda environment requires _any_ version of pandas
4. Augur requires pandas >=1, <2
5. Augur is installed via pip

Because Augur is installed via pip and has more stringent pandas version requirements than the conda environment’s pandas, there is no way for the conda environment to know it should install a later version of pandas. If an older version has already been installed locally and is cached, conda will use it. When conda reaches the pip installation step, the pandas version required is >=1 and <2 which is the _latest_ version and does not support Python 3.6. Since there is no prebuilt wheel for Python 3.6, pip downloads the source code and tries to compile pandas from source.

There a couple of ways we can fix this problem:

- Require at least Python 3.7 in the conda environment, allowing the pip install to grab the latest pandas wheel
- Install [Augur via its Bioconda package](https://bioconda.github.io/recipes/augur/README.html), ensuring that pandas (and other dependencies that are available through conda) are installed with their expected versions from conda instead of pip.
- Require Python >=3.6 and require pandas >=1, <2 in the conda environment, forcing the conda environment to install the latest conda package of pandas (this solution is somewhat redundant with the Augur install from conda, but avoids requirements of a conda-forge channel that can slow installation times.)

I'll link back to this issue from a pull request that should fix it.

**Comment by wasade** [comment]
Sorry, completely dropped the ball on this, got pulled in some other directions a few weeks ago. I haven't had a chance to test @ericenns's solution -- attempting it right now on OSX and will report back when complete. And thank you for the detailed breakdown -- it is never fun when pip and conda butt heads!! 

If it is feasible, it may be beneficial for CI to exercise the installation procedure presented in the documentation.

**Comment by huddlej** [comment]
That is a great idea. We use the Nextstrain CLI + Docker image to run the CI tests because that best represents how we run our jobs internally through AWS. This tension between Docker and conda is one we're trying to resolve, but it has been tricky.

**Comment by wasade** [comment]
The solution from @ericenns worked for install on OSX! :) However, I'm unable to complete the third code cell (`snakemake --cores 4 --profile ./my_profiles/getting_started
`) in step three of the setup process:

```bash
(nextstrain) 10:27:58 (dtmcdonald@here):ncov@master$ snakemake --cores 4 --profile ./my_profiles/getting_started
-bash: snakemake: command not found
```

Unfortunately, a simple `conda` install fails:

```bash
(nextstrain) 10:30:09 (dtmcdonald@here):ncov@master$ conda install -c bioconda snakemake
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - snakemake -> python[version='3.4.*|3.5.*|3.6.*|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```

...although `pip` seemed viable:

```bash
(nextstrain) 10:30:46 (dtmcdonald@here):ncov@master$ pip install snakemake
Collecting snakemake
  Downloading snakemake-5.32.2.tar.gz (254 kB)
     |████████████████████████████████| 254 kB 2.6 MB/s
...SNIP...
Successfully installed amply-0.1.4 appdirs-1.4.4 configargparse-1.3 gitdb-4.0.5 gitpython-3.1.13 ipython-genutils-0.2.0 jupyter-core-4.7.1 nbformat-5.1.2 pulp-2.4 ratelimiter-1.2.0.post0 smmap-3.0.5 snakemake-5.32.2 toposort-1.6 traitlets-5.0.5 wrapt-1.12.1
```

And following the `pip` install, `snakemake` is able to complete successfully! 

For reference, the commit of `ncov` is below:

```bash
(nextstrain) 10:37:26 (dtmcdonald@here):ncov@master$ git --no-pager log -1 --oneline
15e0e429 (HEAD -> master, origin/master, origin/HEAD) Merge branch 'master' of https://github.com/nextstrain/ncov
```

**Comment by huddlej** [comment]
Excellent! Thank you for trying this out, @wasade. The [main Nextstrain environment installs Snakemake via pip](http://data.nextstrain.org/nextstrain.yml), but the workflow version does not yet.

We will update the main environment to use Python >=3.7 and that should fix this problem in the longer term.

**Comment by wasade** [comment]
Great!! Thank you!
