### ISSUE TITLE
Bug in treeanc.py

### ISSUE THREAD

**Issue by EricFournier3** [nextstrain/ncov#727]
Hi,

I have the following error occuring in rule logistic_growth of the ncov workflow:
__________________________________________________________________________________________
Traceback (most recent call last):
  File "scripts/explicit_translation.py", line 34, in <module>
    tt = TreeAnc(tree=T, aln=MultipleSeqAlignment(seqs), alphabet='aa')
  File "/data/Applications/Miniconda/miniconda3/envs/nextstrain_v20210712/lib/python3.8/site-packages/treetime/treeanc.py", line 162, in __init__
    self._check_alignment_tree_gtr_consistency()
  File "/data/Applications/Miniconda/miniconda3/envs/nextstrain_v20210712/lib/python3.8/site-packages/treetime/treeanc.py", line 380, in _check_alignment_tree_gtr_consistency
    raise MissingDataError("TreeAnc._check_alignment_tree_gtr_consistency: At least 30\\% terminal nodes cannot be assigned a sequence!\n"
treetime.MissingDataError: TreeAnc._check_alignment_tree_gtr_consistency: At least 30\% terminal nodes cannot be assigned a sequence!
Are you sure the alignment belongs to the tree?
_____________________________________________________________________________________________
I never had this problem before:

******************
nextstrain.cli 3.0.3
augur 13.0.0
treetime 0.8.4
******************

I attached the log file, the build.yaml and the list of samples kept after filter steps

Can you please help me with this ?
Thanks
Eric
[2021-09-16T091050.108587.snakemake.log](https://github.com/nextstrain/cli/files/7181915/2021-09-16T091050.108587.snakemake.log)
[sample-mycontextual.txt](https://github.com/nextstrain/cli/files/7181918/sample-mycontextual.txt)
[builds.txt](https://github.com/nextstrain/cli/files/7181917/builds.txt)
[sample-myfocal.txt](https://github.com/nextstrain/cli/files/7181919/sample-myfocal.txt)

[sample-myrelated.txt](https://github.com/nextstrain/cli/files/7181920/sample-myrelated.txt)
[detailedSummary.txt](https://github.com/nextstrain/cli/files/7193225/detailedSummary.txt)
[aligned.errors.csv](https://github.com/nextstrain/cli/files/7193316/aligned.errors.csv)

**Comment by EricFournier3** [comment]
Ok thank you Richard,

indeed, it works well now without ORFa
