### ISSUE TITLE
No column named Nextclade_pango

### ISSUE THREAD

**Issue by AdmiralenOla** [nextstrain/ncov#899]
**Current Behavior**
ncov workflow crashes at the join_metadata_and_nextclade_qc rule. The key "Nextclade_pango" doesn't exist in the input files to this rule.

**Expected behavior**
I expected "Nextclade_pango" to be a column in the nextclade_qc.tsv file. It does not seem to be in Nextclade version 1.11.0, which is the version indicated in the most recent pull of workflow/envs/nextstrain.yaml

**How to reproduce**
Steps to reproduce the current behavior:
1. Download gisaid data and point to files in builds.yaml
2. Run snakemake pipeline with default parameters
3. See error:

```
Traceback (most recent call last):
  File "/media/olbb/Utgard/Projects/COVID19/Nextstrain/ncov/.snakemake/conda/dac65a5e0d82365a508f2ea68d52754d/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Nextclade_pango'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/join-metadata-and-clades.py", line 150, in <module>
    main()
  File "scripts/join-metadata-and-clades.py", line 140, in main
    result[col] = result[col].fillna(VALUE_MISSING_DATA)
  File "/media/olbb/Utgard/Projects/COVID19/Nextstrain/ncov/.snakemake/conda/dac65a5e0d82365a508f2ea68d52754d/lib/python3.8/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/media/olbb/Utgard/Projects/COVID19/Nextstrain/ncov/.snakemake/conda/dac65a5e0d82365a508f2ea68d52754d/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'Nextclade_pango'
```

**Versions**
  - augur=14.0.0
  - epiweeks=2.1.2
  - iqtree=2.2.0-beta
  - nextalign=1.11.0
  - nextclade=1.11.0
  - pangolin=3.1.20
  - pangoLEARN=2022.01.20

**Comment by AdmiralenOla** [comment]
Thank you, @huddlej! Well, I really thought I had tested that thoroughly, but running my command with `--forceall` does indeed solve my problem. Apologies for taking up your time with this!

**Comment by huddlej** [comment]
No worries, @AdmiralenOla! It's better to be sure that there's not an issue in the code that everyone else is silently enduring. :) I'm glad it is working now, though.
